grpc:
  server:
    port: ${GRPC_SERVER_PORT:9091}
    security:
      enabled: ${GRPC_SERVER_SECURITY:false}
  client:
    grpc-user-manager-service:
      address: ${GRPC_USER_MANAGER_SERVICE:static://localhost:9090}
      negotiationType: plaintext
security:
  authentication:
    jwt:
      # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
      secret: ${SECURITY_AUTHENTICATION_JWT_SECRET:OGEzMWZkOTQzYTI3ZjMwNTJmNTEwYjUwZjMxN2ZiOTljODgyODhkNTkwMzllYWIyYjVhOTMzNzZkYzM4MzI0NDFmMzJhNmQwZTExNjU3ZTBkZmNmZTY2MzlkYjVlZmNlMjI0M2Y3MWUzN2YwMjczYTU4YmFjZGU0M2MzNzZiNDc=}
      # Token is valid 24 hours
      token-validity-in-seconds: ${JWT_TOKEN_VALIDITY_IN_SECONDS:86400}
      token-validity-in-seconds-for-remember-me: 2592000
    permit-all:
      - /api/user/login
      - /api/user/register
      - /api/telegram/test
    cross-origin:
      - "*"
    credentials: false
    allowed-headers:
      - Content-Type
      - Authorization
    allowed-methods:
      - POST
      - GET
      - PUT
      - DELETE
      - OPTIONS
server:
  port: 8888
  servlet:
    context-path: /x-notification
telegrambot:
  bot-token: ${BOT_TOKEN:your-token}
  bot-username: htv_ip_bot
  chatId : ${CHAT_ID:-1002495395116}
  delete-webhook-on-startup: false
spring:
  application:
    name: x-notification
  mail:
    host: smtp.gmail.com
    port: 587
    username: hatrongvu13@gmail.com
    password: your-pass
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true